// Tasks actions
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS'
export const SAVE_TASKS_SUCCESS = 'SAVE_TASKS_SUCCESS'

// UI actions
export const SET_IS_DATA_READY = 'SET_IS_DATA_READY'
export const SET_DATA_LOADING_ERROR = 'SET_DATA_LOADING_ERROR'
export const UPDATE_NUMBER_OF_AJAX_CALLS = 'UPDATE_NUMBER_OF_AJAX_CALLS'

export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
